---
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Remove the container if exist
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_name }}"
        state: absent
    - name: Remove image if exist
      docker_image:
        name: "{{ default_container_name }}"
        state: absent
    - name: Create image
      docker_image:
        name: "{{ default_container_name }}"
        path: /var/local/src/instance-bootstrap/flask-application
        state: present
    - name: Run the container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_name }}"
        state: started
        ports:
          - "80:5000"
